export const USER_LOADING = 'FETCH_USER_LOADING';
export const USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const USER_FAILURE = 'FETCH_USER_FAILURE';

export const SIGNUP_USER_LOADING = 'SIGNUP_USER_LOADING';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const LOGINUSER_LOADING = 'LOGIN_USER_LOADING';
export const LOGINUSER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGINUSER_FAILURE = 'LOGIN_USER_FAILURE';
